# Generated by Django 5.1.7 on 2025-07-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wells',
            name='depth_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wells',
            name='depth_stop',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
