# Generated by Django 5.1.7 on 2025-07-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_wells_depth_start_wells_depth_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlas',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.wells'),
        ),
    ]
