# Generated by Django 5.1.7 on 2025-07-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_uploadlas_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='wells',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wells',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
