# Generated by Django 5.1.7 on 2025-07-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_wells_operator_wells_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wells',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
