# Generated by Django 5.1.7 on 2025-07-17 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_alter_wells_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('time', models.FloatField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wells')),
            ],
        ),
        migrations.CreateModel(
            name='DeviationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md', models.FloatField()),
                ('incl', models.FloatField()),
                ('azim', models.FloatField()),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wells')),
            ],
        ),
        migrations.CreateModel(
            name='WellHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.wells')),
            ],
        ),
    ]
